### ISSUE TITLE
Use with a webserver

### ISSUE THREAD

**Issue by ghost** [enyosolutions-team/nginx-vhost-admin#2]
Good solution. I have installed it, made a own local.js and started up. 
However I get the following errors:
- Restart button nginx: {"errors"[error_no_authorisation_header_for_agent"],"message":"error_no_authorisation_wrong_format_for_agent"}
- Selecting Dashboard: Error_no_autorisation_wrong_format_for_agent

**Comment by Signe93** [comment]
Same here. Wanted to use it but I'm getting the same error. Tried to disable all the checks in the isAuthorized class just for test, but then even more errors are coming :/

**Comment by fbatiga** [comment]
helo there. For Some i never got notified of the issues you created. 

Have you been able to fix the issue

@Signe93

**Comment by fbatiga** [comment]
This error is simply because there is no authKey defined in your local.js
